solution added
mate-academy/react_static-list-of-posts-js pull request #1010
Opened 2024-07-26 16:48 UTC by happytravels38

[DEMO LINK](https://happytravels38.github.io/react_static-list-of-posts-js/)

2024-07-26 17:54 UTC, anastasiiavorobiova requested changes
Great work! Added a few comments to fix

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/CommentInfo/CommentInfo.jsx
> +  <>
```suggestion

```
No need to use fragments if you have common parent element

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/CommentInfo/CommentInfo.jsx
> +export const CommentInfo = ({ comment }) => (
Consider using destructuring here

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/PostInfo/PostInfo.jsx
> +export const PostInfo = ({ post }) => (
Consider using destructuring here

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/PostList/PostList.jsx
> +  </>
```suggestion

    <div className="PostList">
      {posts.map(post => (
        <PostInfo key={post.id} post={post} />
      ))}
    </div>

```

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/UserInfo/UserInfo.jsx
> +  <>
```suggestion

```

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/UserInfo/UserInfo.jsx
> +  </>
```suggestion

```

2024-07-26 17:54 UTC, anastasiiavorobiova commented on src/components/UserInfo/UserInfo.jsx
> +export const UserInfo = ({ user }) => (
Consider using destructuring here

2024-07-27 06:38 UTC, volodymyr-soltys97 approved these changes
Good job 👍

2024-07-27 06:38 UTC, volodymyr-soltys97 commented on src/components/PostInfo/PostInfo.jsx
> +    {comments && comments.length > 0 ? (
```suggestion
    {comments && !!comments.length ? (
```

2025-06-16 18:47 UTC, closed without merging