add task solution
mate-academy/react_static-list-of-posts-js pull request #113
Opened 2023-07-18 08:07 UTC by AndriiYelieva

[DEMO](https://AndriiYelieva.github.io/react_static-list-of-posts-js/)

2023-07-18 09:43 UTC, IvanFesenko requested changes
Good job. Check few comments

2023-07-18 09:43 UTC, IvanFesenko commented on src/components/CommentInfo/CommentInfo.jsx
> +
```suggestion
      <span> by </span>
```

2023-07-18 09:43 UTC, IvanFesenko commented on src/components/PostInfo/PostInfo.jsx
> +        {' Posted by  '}
Same here - better to wrap by tag

2023-07-18 09:43 UTC, IvanFesenko commented on src/components/PostInfo/PostInfo.jsx
> +        <UserInfo user={post.user} />
User might be null so add check if user exists

2023-07-20 06:29 UTC, etojeDenys approved these changes
awesome

2024-09-12 11:01 UTC, closed without merging