solution
mate-academy/react_static-list-of-posts-js pull request #1203
Opened 2024-11-21 10:36 UTC by Fridrif27

[DEMO LINK] (https://fridrif27.github.io/react_static-list-of-posts-js/)

2024-11-21 12:08 UTC, StricTGod approved these changes

2024-11-21 13:25 UTC, mateacademy-ai-mentor approved these changes
Your code meets the task requirements and constraints effectively! 🎉 The components are well-structured, and the logic for rendering posts and comments is correctly implemented. While some tests are commented out, it seems intentional for debugging or development purposes. Ensure all necessary tests are active to fully verify your components. Great job overall, and keep up the good work! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-11-21 13:25 UTC, mateacademy-ai-mentor commented on src/components/PostInfo/PostInfo.spec.jsx
> +    // });
These tests are commented out. If they are needed, consider uncommenting them to ensure the `PostInfo` component is thoroughly tested for displaying comments and the absence of the 'NoCommentsMessage'.

2024-11-21 13:25 UTC, mateacademy-ai-mentor commented on src/components/PostInfo/PostInfo.spec.jsx
> +    // });
This test is also commented out. If you want to verify the rendering of another post, consider uncommenting it. Ensure all necessary tests are active to cover different scenarios.

2024-11-25 18:33 UTC, BudnikOleksii requested changes
Uncomment tests and fix your solution in accordance

2024-11-25 18:33 UTC, BudnikOleksii commented on src/App.jsx
> +        comments={commentsFromServer}
Prepare posts with user and comments and use it instead

2024-11-25 18:33 UTC, BudnikOleksii commented on src/components/CommentList/CommentList.jsx
> +  if (!comments || comments.length === 0) {
You don't need to render `CommentList` component at all if you don't have comments

2024-11-25 18:33 UTC, BudnikOleksii commented on src/components/CommentList/CommentList.jsx
> +        <CommentInfo key={c.id} comment={c} />
What is `c`? Avoid one-letter names

2024-11-25 18:33 UTC, BudnikOleksii commented on src/components/PostInfo/PostInfo.spec.jsx
> +    //     );
Uncomment all tests

2024-12-31 07:47 UTC, closed without merging