done but 1 test failed i dk why
mate-academy/react_static-list-of-posts-js pull request #125
Opened 2023-07-22 18:45 UTC by maxonshev

https://maxonshev.github.io/react_static-list-of-posts-js/

Виникає помилка при npm test.
Але ці елементи відображаються на сторінці
1) CommentInfo component
       should show a name:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.CommentInfo__name`, but never found it.
      at $Chainer.<computed> [as should] (http://localhost:53445/__cypress/runner/cypress_runner.js:188813:176)
      at Context.<anonymous> (http://localhost:53445/__cypress/src/static/js/spec-0.chunk.js:43:34)
      at Context.runnable.fn (http://localhost:53445/__cypress/runner/cypress_runner.js:190621:19)
      at callFn (http://localhost:53445/__cypress/runner/cypress_runner.js:142741:21)
      at http://localhost:53445/__cypress/runner/cypress_runner.js:197534:30
      at PassThroughHandlerContext.finallyHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:22856:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:53445/__cypress/runner/cypress_runner.js:26302:23)
      at Promise._settlePromiseFromHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:24237:31)

  2) CommentInfo component
       should show an email:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.CommentInfo__email`, but never found it.
      at $Chainer.<computed> [as should] (http://localhost:53445/__cypress/runner/cypress_runner.js:188813:176)
      at Context.<anonymous> (http://localhost:53445/__cypress/src/static/js/spec-0.chunk.js:46:35)
      at Context.runnable.fn (http://localhost:53445/__cypress/runner/cypress_runner.js:190621:19)
      at callFn (http://localhost:53445/__cypress/runner/cypress_runner.js:142741:21)
      at http://localhost:53445/__cypress/runner/cypress_runner.js:197534:30
      at PassThroughHandlerContext.finallyHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:22856:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:53445/__cypress/runner/cypress_runner.js:26302:23)
      at Promise._settlePromiseFromHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:24237:31)

  3) CommentInfo component
       should show a body:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.CommentInfo__body`, but never found it.
      at $Chainer.<computed> [as should] (http://localhost:53445/__cypress/runner/cypress_runner.js:188813:176)
      at Context.<anonymous> (http://localhost:53445/__cypress/src/static/js/spec-0.chunk.js:49:34)
      at Context.runnable.fn (http://localhost:53445/__cypress/runner/cypress_runner.js:190621:19)
      at callFn (http://localhost:53445/__cypress/runner/cypress_runner.js:142741:21)
      at http://localhost:53445/__cypress/runner/cypress_runner.js:197534:30
      at PassThroughHandlerContext.finallyHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:22856:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:53445/__cypress/runner/cypress_runner.js:26302:23)
      at Promise._settlePromiseFromHandler (http://localhost:53445/__cypress/runner/cypress_runner.js:24237:31)

2023-07-23 07:34 UTC, etojeDenys requested changes

2023-07-23 07:34 UTC, etojeDenys commented on src/App.jsx
> +  return usersFromServer.find(user => user.id === userId);
```suggestion
  return usersFromServer.find(user => user.id === userId) || null;
```

2023-07-23 07:34 UTC, etojeDenys commented on src/components/PostInfo/PostInfo.jsx
> +          <UserInfo user={user} key={id} />
we don't need to pass key prop here
and user can be null so we need to handle this case here

2023-07-24 08:59 UTC, ivbutsykin approved these changes
Good job!

2023-07-24 08:59 UTC, ivbutsykin commented on src/components/CommentInfo/CommentInfo.jsx
> +export const CommentInfo = ({ comment: { name, email, body } = [] }) => (
A little bit strange that `comment` is empty array by default)

Looks like your component will crash if accept it (`[]`)

2025-03-07 10:43 UTC, closed without merging