solution
mate-academy/react_static-list-of-posts-js pull request #485
Opened 2023-12-03 16:17 UTC by venher-v

https://venher-v.github.io/react_static-list-of-posts-js/

2023-12-03 17:47 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2023-12-03 17:47 UTC, anastasiiavorobiova commented on src/App.jsx
> +    || null;
```suggestion

```
This function never returns a null

2023-12-03 17:47 UTC, anastasiiavorobiova commented on src/components/PostInfo/PostInfo.jsx
> +          <UserInfo
```suggestion
          user && <UserInfo
```

2023-12-03 17:47 UTC, anastasiiavorobiova commented on src/components/PostInfo/PostInfo.jsx
> +          <UserInfo
Consider adding a check if the user exists

2023-12-04 08:05 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2024-08-08 16:53 UTC, closed without merging