task solution
mate-academy/react_static-list-of-posts-js pull request #675
Opened 2024-02-27 15:56 UTC by BoGoBooM

[DEMO LINK](https://bogoboom.github.io/react_static-list-of-posts-js/)

2024-02-27 16:28 UTC, nazarmatsevych requested changes
Good work, please fix the comment below

2024-02-28 07:23 UTC, etojeDenys requested changes

2024-02-28 07:23 UTC, etojeDenys commented on src/components/PostInfo/PostInfo.jsx
> +        <UserInfo user={post.user} />
user can be undefined, let's render the component only when the user exists
```suggestion
        {post.user && <UserInfo user={post.user} />}
```

2024-02-28 18:19 UTC, etojeDenys approved these changes
good job

2024-02-28 18:19 UTC, etojeDenys commented on src/components/PostInfo/PostInfo.jsx
> +      ``
```suggestion
      
```

2025-02-17 11:52 UTC, closed without merging