create-post
mate-academy/react_static-list-of-posts-js pull request #927
Opened 2024-06-09 20:21 UTC by Pashahu1

[DEMO LINK](https://Pashahu1.github.io/react_static-list-of-posts-js/)

2024-07-23 21:46 UTC, AndriiZakharenko requested changes
good job!
please, update Demo Link

2024-07-24 06:07 UTC, AndriiZakharenko approved these changes

2024-07-24 07:14 UTC, BudnikOleksii approved these changes
Good work 👍

2024-07-24 07:14 UTC, BudnikOleksii commented on src/App.jsx
> +const prepareData = () => {
```suggestion
const preparePosts = () => {
```
Specify what kind of data you prepare

2024-07-24 07:14 UTC, BudnikOleksii commented on src/components/CommentInfo/CommentInfo.jsx
> +        {comment.email}
Use destructuring so you don't need to repeat every time `comment.email`/etc

2026-03-17 04:35 UTC, closed without merging